### ISSUE TITLE
Can't download data

### ISSUE THREAD

**Issue by SerenaOwens** [ncbi/rapt#14]
I ran an SRA sequence and am attempting to download the data for that sequence, but it comes up with a "404 page not found" error. How can I fix this issue?

**Comment by mingzhangyang** [comment]
Hi @SerenaOwens , have you been able to download your result files? We were rolling out a new version when you came across the 404 error. It should be a transient issue. Please let us know if you still see the error.

**Comment by mingzhangyang** [comment]
It is a transient issue and has been gone.
