### ISSUE TITLE
Paired end reads

### ISSUE THREAD

**Issue by rfcohen** [ncbi/rapt#7]
How to feed paired end reads into RAPT?  It's not clear from he documentation how one feeds paired end reads into RAPT.

Thanks.

**Comment by thibaudnis** [comment]
You can provide a file of paired-end reads, with the two reads of a pair adjacent to each other in the file (i.e. spot 1 fwd, spot 1 rev, spot 2 fwd, spot 2 rev) . We will add this to the doc shortly. Thanks for pointing out the omission.

**Comment by rfcohen** [comment]
Thank you. But actually I want to provide two files, R1 and R2 separately. 

-Rob

**Comment by thibaudnis** [comment]
This is not currently supported.

**Comment by rfcohen** [comment]
Looks like SKESA supports it. Also SKESA supports inputting Gzip’d files which would be nice, or at least documented that RAPT does accept compressed files.

Thanks. 

-Rob

**Comment by thibaudnis** [comment]
Yep, thanks for the suggestions!

**Comment by buihoangphuc412** [comment]
I have 2 files: R1 and R2, I seem like RAPT did not support
./run_rapt_gcp.sh submitfastq gs://buihoangphuc412/VN0211-s_1_1_sequence.qf.fastq.gz gs://buihoangphuc412/VN0211-s_1_2_sequence.qf.fastq.gz -b gs://buihoangphuc412/VN0211 --organism "Helicobacter pylori" --strain "VN0211"

**Comment by thibaudnis** [comment]
Okay, I see we need to start accepting R1 and R2. In the meantime, there seems to be a number of options out there for combining the two files: [interleave-fastq](https://github.com/ekg/interleave-fastq/), or reformat.sh in the [BBmap suite](https://sourceforge.net/projects/bbmap/) that may help.

**Comment by thibaudnis** [comment]
@buihoangphuc412 and @rfcohen: starting with v0.3.0, you can now provide the forward and reverse reads of a run in separate files, and these files can be gzipped. This version of RAPT is also much faster. See announcement for this new release: https://ncbiinsights.ncbi.nlm.nih.gov/2021/02/12/rapt-release/ . Thanks for your feedback!
